[workspace]
resolver = "2"
members = ["shai-macros", "shai-llm", "shai-core", "shai-cli", "shai-http"]

[patch.crates-io]
ratatui = { git = "https://github.com/Marlinski/ratatui", branch = "feature/viewport-resize-v29" }